In [1]:
import pandas as pd            
import os

# Check the cwd
os.getcwd()

'c:\\Users\\casaz\\Documents\\Simone\\University\\dhdk\\thesis\\evalita_task\\evalita2026-multipride-UniBO-FICLIT'

In [2]:
# Import data from CSV
data = pd.read_csv('data/train_it.csv')
data

,id,text,bio,label,lang
0,it_1231,La destra Italiana pur di non dire che loro od...,Il rispetto per il prossimo qualunque sia il s...,0,it
1,it_1713,"""Presupporre che tutti i bisessuali non sono m...",𝓕𝓲𝓵𝓵𝓮𝓭 𝔀𝓲𝓽𝓱 𝓯𝓾𝓻𝔂 𝓪𝓷𝓭 𝓼𝓽𝓪𝓻𝓻𝔂 𝓮𝔂𝓮𝓭,0,it
2,it_1474,"Se i diritti devono essere uguali, voglio che ...",User Experience Designer URL,0,it
3,it_58,che poi molti uomini trans subiscono lesbofobi...,"no matter where i go, you're there …",0,it
4,it_511,Che poi è l’etero medio come Pio e Amedeo che ...,T'appartengo ed io ci tengo \nE se prometto po...,0,it
...,...,...,...,...,...
1081,it_1340,Io mi sono rotto i coglioni di tutte queste po...,"Se incapaci di scherzare, se il resto del mond...",0,it
1082,it_595,"come una donna cis non può subire transfobia, ...",알잖아 널 가만히 둘 수 없는 걸,0,it
1083,it_844,Ehi comunità @USER questo giornalista di repub...,NaN,0,it
1084,it_1216,"@USER tom felton non è transfobico, ma ha anch...",NaN,0,it
1085,it_521,rivolta frocia tutti i giorni porcodio,mi piace cacare in compagnia,1,it

In [3]:
# some basic stats
print(len(data))
print(data['label'].value_counts())
print(data.info())

1086
0    879
1    207
Name: label, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1086 entries, 0 to 1085
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      1086 non-null   object
 1   text    1086 non-null   object
 2   bio     1000 non-null   object
 3   label   1086 non-null   int64
 4   lang    1086 non-null   object
dtypes: int64(1), object(4)
memory usage: 42.5+ KB
None

In [4]:
# Print average length of texts in tokens
data['text_length'] = data['text'].apply(lambda x: len(x.split()))
print(data['text_length'].mean())

# Print average length of biographies in tokens (if available, otherwise do not count them)
data['bio_length'] = data['bio'].apply(lambda x: len(x.split()) if pd.notnull(x) else None)
print(data['bio_length'].mean())

34.06813996316759
13.302

In [5]:
# Import hurtlex data from TSV
hurtlex = pd.read_csv('data/hurtlex_IT.tsv', sep='\t')

hurtlex.head()

       id pos category stereotype         lemma      level
0  IT2787   n       om         no             ⚣  inclusive
1  IT1289   n      cds         no      carretta  inclusive
2  IT4202   n      cds         no  qualunquista  inclusive
3  IT1197   n      cds         no       albagia  inclusive
4  IT3452   n       an         no      porcello  inclusive

In [6]:
homophobic_terms = hurtlex[hurtlex['category'] == "om"]

homophobic_terms

          id pos category stereotype                   lemma         level
0     IT2787   n       om         no                       ⚣     inclusive
31    IT3992   a       om         no                anormale     inclusive
151   IT1374   n       om         no                 codardo  conservative
177    IT392   n       om         no                 buricco     inclusive
212   IT1653   n       om         no                    poof  conservative
...      ...  ..      ...        ...                     ...           ...
6633  IT2108   n       om         no  linea medioclavicolare     inclusive
6644  IT2132   n       om         no                  dietro     inclusive
6661  IT2126   n       om         no            fondoschiena     inclusive
6721  IT2129   n       om         no                deretano     inclusive
6731  IT2338   n       om         no   portatore-di-handicap  conservative

[145 rows x 6 columns]

In [7]:
# create a set of homophobic terms for faster lookup
homophobic_set = set(homophobic_terms['lemma'].str.lower())

In [ ]:
# Check for homophobic terms in the tweets end return a column with the terms found
def contains_homophobic_term(text):
    words = text.lower().split()
    for word in words:
        if word in homophobic_set:
            return word
    return None
data['contains_homophobic'] = data['text'].apply(contains_homophobic_term)
data[['text', 'contains_homophobic']]

                                                   text contains_homophobic
0     La destra Italiana pur di non dire che loro od...         omosessuali
1     "Presupporre che tutti i bisessuali non sono m...                None
2     Se i diritti devono essere uguali, voglio che ...                None
3     che poi molti uomini trans subiscono lesbofobi...                None
4     Che poi è l’etero medio come Pio e Amedeo che ...                None
...                                                 ...                 ...
1081  Io mi sono rotto i coglioni di tutte queste po...                 gay
1082  come una donna cis non può subire transfobia, ...                None
1083  Ehi comunità @USER questo giornalista di repub...            finocchi
1084  @USER tom felton non è transfobico, ma ha anch...                None
1085             rivolta frocia tutti i giorni porcodio                None

[1086 rows x 2 columns]

In [ ]:
# Drop rows with None values in 'contains_homophobic' column
data_with_homophobic = data.dropna(subset=['contains_homophobic'])

data_with_homophobic[['text', 'contains_homophobic']]

                                                   text contains_homophobic
0     La destra Italiana pur di non dire che loro od...         omosessuali
7     ⚫️ MA LA VIOLENZA CONTRO I GAY E I TRANS PROPR...                 gay
9     Odiata dai queer di twitter, dalle terf, dal t...               queer
10    @USER Perché se sono finocchi che vogliono dev...            finocchi
17    @USER @USER io ci vengo ai vostri raduni Gay P...                 gay
...                                                 ...                 ...
1074  #omotransfobia O misoginia? Alzi la mano chi n...                 gay
1078  Gli eroi del momento delle canaglie liberal e ...          travestito
1079  @USER manco mi offendo io sono finocchio nel c...           finocchio
1081  Io mi sono rotto i coglioni di tutte queste po...                 gay
1083  Ehi comunità @USER questo giornalista di repub...            finocchi

[282 rows x 2 columns]

In [13]:
data_with_homophobic[data_with_homophobic['contains_homophobic'] == 'frocio'][['text', 'contains_homophobic', 'label']]

,text,contains_homophobic,label
67,Sono frocio ma - a differenza sua che guarda s...,frocio,1
99,@USER non la perdono fino a che non viene al P...,frocio,1
102,MA QUALE DIRITTI? IL DIRITTO DI ESSERE FROCIO ...,frocio,0
105,"@USER Sarò ripetitiva,ma da uno che dice orgog...",frocio,0
153,@USER @USER L'ovvio??? Bestemmiare è dire l'ov...,frocio,0
228,pronto a combattere l'omofobia con l'auto iron...,frocio,1
234,a volte esagerate con l'osannare achille lauro...,frocio,1
239,2 mesi fa se davi del frocio a uno la gente pa...,frocio,0
265,@USER @USER Hai un arcobaleno nel nick. Hai un...,frocio,0
290,@USER CHRIS NON SIAMO IN UNA CAZZO DI FANFICTI...,frocio,0
297,@USER Se tu sei frocio e orgoglioso di esserlo...,frocio,0
308,#FedezDDLZAN attivista per i diritti #gay crea...,frocio,0
314,e siete etero? Siete queer'. Capito? Usano un ...,frocio,0
322,@USER Continui a non capire coglione che mentr...,frocio,1
325,Sarri ha un limite evidente. La prima volta si...,frocio,0
330,tipo 'siete in coppia aperta e siete etero? Si...,frocio,0
336,@USER Un po’ come #omofobia è colpa mia che so...,frocio,1
345,E' un pensiero poverissimo quello di ritenere ...,frocio,0
383,@USER Mo che lui abbia fatto il frocio coi dir...,frocio,0
385,"@USER Il paladino LGBT, i cui testi:\n «Non fa...",frocio,0
415,"@USER Perché Zaki è frocio e loro, il PD, si o...",frocio,0
426,"@USER straight, etero in modo dispregiativo pa...",frocio,1
449,@USER @USER Padre e Madre. Su richiesta altri ...,frocio,0
470,io sottomesso solo da lana del rey lei può chi...,frocio,1
491,i miei diritti da frocio triste e con un piede...,frocio,1
503,dici anche frocio da ally etero cisgender? 😍🏳️...,frocio,0
516,il la spezia pride non so se verrei pestato pr...,frocio,1
541,Pinocchio frocio e la principessa lesbica: il ...,frocio,0
590,Da frocio vorrei dire grazie a #PioAmedeo. Sie...,frocio,1
593,chi pensa che il problema sia l'omofobia è IL ...,frocio,1
602,"non fedez, che voi avete decretato paladino de...",frocio,0
623,"Primario accusato di omofobia sospeso: ""Vedi s...",frocio,0
648,@USER Ha votato una persona che nega i miei di...,frocio,1
702,A me personalmente personalmente non interessa...,frocio,0
713,"@USER Oh frocione il mese del pride e finito, ...",frocio,0
729,io domani merito 30 e lode solo perché sono fr...,frocio,1
774,@USER @USER I diritti di noi italiani cosa è d...,frocio,0
814,"""Si deve vergognare, uno così non può stare ne...",frocio,1
849,@USER amo ma sti cazzi secondo me chiunque del...,frocio,1
850,Per inciso: il “frocio di m.” era il paziente ...,frocio,0
857,Dire Frocio è una parola che non si può più us...,frocio,0
910,Siamo in1paese in cui se dici frocio in prima ...,frocio,0
945,tommaso è da anni che lotta per i suoi diritti...,frocio,0
953,come quando “ma frocio non mi sembra un insult...,frocio,0
964,“La cattiveria non è mai nella lingua ma nelle...,frocio,0
983,"""Se ho un foglio frocio lo uccido""\nQuel figli...",frocio,0
985,"@USER metallaro, fifone e pure frocio\nsono se...",frocio,1
988,@USER @USER E vero dire frocio non e un offesa...,frocio,0
999,Attivista #LGBT aggredito dal branco a #Milano...,frocio,0
1022,"Fra siamo letteralmente gay, posso usare le pa...",frocio,1
1024,@USER Io da orgoglioso FROCIO dico ci avete pr...,frocio,1
1045,@USER a frocio succhia melenzane !\na ricchion...,frocio,0
1050,Siete pronti e pronte a subirci un mese di azi...,frocio,1
1066,credi che qui si combattá per un frocio che ti...,frocio,1